"""Update the check dates

Revision ID: ebc671a982a8
Revises: 7b443b287777
Create Date: 2024-02-23 12:04:32.196632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc671a982a8'
down_revision = '7b443b287777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'default_role'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'default_role'::character varying"))

    with op.batch_alter_table('property_listings', schema=None) as batch_op:
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')

    # ### end Alembic commands ###
